export let countrys = [
    {
        delegatName: 'Гусейнов Артемий',
        countryName: 'Республика Индия',
        countriStatus: false,
        countriFlag: 'in',
    },
    {
        delegatName: 'Кутбитдинов Джахонгир',
        countryName: 'Новая Зеландия',
        countriStatus: false,
        countriFlag: 'nz',
    },
    {
        delegatName: 'Князев Никита',
        countryName: 'Королевство Таиланд',
        countriStatus: false,
        countriFlag: 'th',
    },
    {
        delegatName: 'Вохобжонова Муслима',
        countryName: 'Королевство Бельгия',
        countriStatus: false,
        countriFlag: 'be',
    },
    {
        delegatName: 'Батырова Жасмина',
        countryName: 'Арабская Республика Египет',
        countriStatus: false,
        countriFlag: 'eg',
    },
    {
        delegatName: 'Гаджиева Патимат',
        countryName: 'Аргентинская Республика',
        countriStatus: false,
        countriFlag: 'ar',
    },
    {
        delegatName: 'Алиев Акмаль',
        countryName: 'Мексиканские Соединённые Штаты',
        countriStatus: false,
        countriFlag: 'mx',
    },
    {
        delegatName: 'Юлдашева Диёра',
        countryName: 'Турецкая Республика',
        countriStatus: false,
        countriFlag: 'tr',
    },
    {
        delegatName: 'Артыкова Шукрона',
        countryName: 'Республика Узбекистан',
        countriStatus: false,
        countriFlag: 'uz',
    },
    {
        delegatName: 'Рустамова Шахина',
        countryName: 'Итальянская Республика',
        countriStatus: false,
        countriFlag: 'it',
    },
    {
        delegatName: 'Басидова Сабрина',
        countryName: 'Ирландия',
        countriStatus: false,
        countriFlag: 'ie',
    },
    {
        delegatName: 'Хошимова Омина',
        countryName: 'Государство Япония',
        countriStatus: false,
        countriFlag: 'jp',
    },
    {
        delegatName: 'Туляганов Самандар',
        countryName: 'Украина',
        countriStatus: false,
        countriFlag: 'ua',
    },
    {
        delegatName: 'Гариб Артём',
        countryName: 'Федеративная Республика Бразилия',
        countriStatus: false,
        countriFlag: 'br',
    },
    {
        delegatName: 'Абдул-Ахадова Амина',
        countryName: 'Республика Казахстан',
        countriStatus: false,
        countriFlag: 'kz',
    },
    {
        delegatName: 'Зуфарова Лазиза',
        countryName: 'Королевство Испания',
        countriStatus: false,
        countriFlag: 'es',
    },
    {
        delegatName: 'Ибрагимов Мирфайз',
        countryName: 'Соединенные Штаты Америки',
        countriStatus: false,
        countriFlag: 'us',
    },
    {
        delegatName: 'Якшигулова Амалия',
        countryName: 'Республика Филиппины',
        countriStatus: false,
        countriFlag: 'ph',
    },
    {
        delegatName: 'Алиходжаева Комила',
        countryName: 'Королевство Нидерландов',
        countriStatus: false,
        countriFlag: 'nl',
    },
    {
        delegatName: 'Латипов Ахмадхон',
        countryName: 'Австрийская Республика',
        countriStatus: false,
        countriFlag: 'at',
    },
    {
        delegatName: 'Акромхожаев Бобур',
        countryName: 'Канада',
        countriStatus: false,
        countriFlag: 'ca',
    },
    {
        delegatName: 'Шарипов Саид',
        countryName: 'Французская Республика',
        countriStatus: false,
        countriFlag: 'fr',
    },
    {
        delegatName: 'Султанова Камола',
        countryName: 'Федеративная Республика Германия',
        countriStatus: false,
        countriFlag: 'de',
    },
    {
        delegatName: 'Ан Вероника',
        countryName: 'Австралийский Союз',
        countriStatus: false,
        countriFlag: 'au',
    },
    {
        delegatName: 'Даминов Тимур',
        countryName: 'Российская Федерация',
        countriStatus: false,
        countriFlag: 'ru',
    },
    {
        delegatName: 'Абдурахманова Малика',
        countryName: 'Королевство Швеция',
        countriStatus: false,
        countriFlag: 'se',
    },
    {
        delegatName: 'Жумагалиева Мадина',
        countryName: 'Алжирская Народная Демократическая Республика',
        countriStatus: false,
        countriFlag: 'dz',
    },
    {
        delegatName: 'Адахамов Аслан',
        countryName: 'Монгольская Народная Республика',
        countriStatus: false,
        countriFlag: 'mn',
    },
    {
        delegatName: 'Шукуруллаев Сухроб',
        countryName: 'Швейцарская Конфедерация',
        countriStatus: false,
        countriFlag: 'ch',
    },
    {
        delegatName: 'Цань Богдан',
        countryName: 'Республика Беларусь',
        countriStatus: false,
        countriFlag: 'by',
    },
    {
        delegatName: 'Хасанов Хайруллох',
        countryName: 'Республика Сингапур',
        countriStatus: false,
        countriFlag: 'sg',
    },
    {
        delegatName: 'Джураев Абдунаим',
        countryName: 'Республика Кыргызстан',
        countriStatus: false,
        countriFlag: 'kg',
    },
    {
        delegatName: 'Абдуазимова Эъзоза',
        countryName: 'Корейская Народно-Демократическая Республика',
        countriStatus: false,
        countriFlag: 'kp',
    },
    {
        delegatName: 'Сайдуллаева Согдиана',
        countryName: 'Соединенное Королевство Великобритании и Северной Ирландии',
        countriStatus: false,
        countriFlag: 'gb',
    },
    {
        delegatName: 'Ходжимуратова Садина',
        countryName: 'Королевство Норвегия',
        countriStatus: false,
        countriFlag: 'no',
    },
    {
        delegatName: 'Саидакмалова Джамиля',
        countryName: 'Республика Грузия',
        countriStatus: false,
        countriFlag: 'ge',
    },
    {
        delegatName: 'Камолитдинова Азиза',
        countryName: 'Республика Польша',
        countriStatus: false,
        countriFlag: 'pl',
    },
    {
        delegatName: 'Маматханов Абдулмалик',
        countryName: 'Федеративная Республика Нигерия',
        countriStatus: false,
        countriFlag: 'ng',
    },
    {
        delegatName: 'Алимов Абдусалом',
        countryName: 'Греческая Республика',
        countriStatus: false,
        countriFlag: 'gr',
    },
    {
        delegatName: 'Мустафаев Санжарбек',
        countryName: 'Республика Корея',
        countriStatus: false,
        countriFlag: 'kr',
    },
    {
        delegatName: 'Азимова Тамила',
        countryName: 'Республика Армения',
        countriStatus: false,
        countriFlag: 'am',
    },
    {
        delegatName: 'Агзамходжаева Муслима',
        countryName: 'Чешская Республика',
        countriStatus: false,
        countriFlag: 'cz',
    },
    {
        delegatName: 'Хамраев Азизбек',
        countryName: 'Исламская Республика Иран',
        countriStatus: false,
        countriFlag: 'ir',
    },
    {
        delegatName: 'Зуфаров Имрон',
        countryName: 'Объединённые Арабские Эмираты',
        countriStatus: false,
        countriFlag: 'ae',
    },
]
